### ISSUE TITLE
Feature or bug: widths do not stack up

### ISSUE THREAD

**Issue by jufemaiz** [roscoelabs/beams#10]
![screenshot 2014-12-29 22 07 15 2](https://cloud.githubusercontent.com/assets/16481/5568147/410b58a2-8fa7-11e4-816e-8359b4bc5fb7.png)

Guys, understanding the box model is rather critical, and if a framework that is failing to comprehend columnar structures when implemented in HTML/CSS then there's going to be some major issues ahead (not to mention the syntactical structure for the columns is awkward at best :\).

Learn from examples of a number of other major frameworks (or their base grid frameworks).

**Comment by peteramckay** [comment]
Thanks for your comment, jufemaiz. Will definitely fix. Two quick followup questions of my own:

- In terms of structure, do you specifically not like the concept of a full-width "beams" element with child elements of 1-20 columns? Or were you referring to something else? 

- Are there other frameworks you'd recommend that deal with this issue better? So far, I'd say our primary influences have been Skeleton and, to a lesser extent, Bootstrap. But if you have other personal favs, I'm glad to hear. Just curious.

**Comment by jufemaiz** [comment]
Hi @peteramckay, the above screenshot was from your own website. The grid failing is the an alignment issue between the columns whereby they do not add up to the full width of the parent element. Hence the ragged edge to the right, completely obliterating its usefullness as a grid structure.

Bootstrap isn't bad, neither are the older 960gs etc.

**Comment by peteramckay** [comment]
Just did some tweaks to CSS to resolve this issue in both the main Beams repo and roscoelabs.com. Here's screen capture of how the grid demo looks on the site now:

![newgrid](https://cloud.githubusercontent.com/assets/1532476/5812617/4e21800c-a023-11e4-8cc5-3e8e113792d7.png)
